package dev.matheus.fluviapp.services.repository.firebase.documents

import dev.matheus.fluviapp.model.passagem.Passagem

data class PassagemDocumento(
    val numero: String = "",
    val viagem: ViagemDocumento? = null,
    val dataViagem: String = "",
    val horaViagem: String = "",
    val passageiro1: PassageiroDocumento? = null,
    val passageiro2: PassageiroDocumento? = null,
    val passageiro3: PassageiroDocumento? = null,
    val veiculo: VeiculoDocumento? = null,
    val agencia: String = "",
    val agente: String = "",
    val valorPago: Double? = null,
    val valorPix: Double? = null,
    val valorDinheiro: Double? = null,
    val valorDebito: Double? = null,
    val valorCredito: Double? = null,
    val desconto: Double? = null,
    val observacao: String? = null,
    val tipoPassagem: String? = null,
    val gratuidade: String? = null,
    val acomodacao: String? = null,
    val funcionarioResponsavel: String = "",
    val status: String = ""
)

fun PassagemDocumento.toPassagem(id: String): Passagem {
    return Passagem(
        id = id,
        numero = numero,
        codigoViagem = viagem?.codigo.orEmpty(),
        empresa = viagem?.empresa.orEmpty(),
        navio = viagem?.navio.orEmpty(),
        origem = viagem?.origem.orEmpty(),
        destino = viagem?.destino.orEmpty(),
        dataViagem = dataViagem,
        horaViagem = horaViagem,
        agencia = agencia,
        agente = agente,
        valorPago = valorPago,
        valorPix = valorPix,
        valorDinheiro = valorDinheiro,
        valorDebito = valorDebito,
        valorCredito = valorCredito,
        desconto = desconto,
        observacao = observacao,
        tipoPassagem = tipoPassagem,
        gratuidade = gratuidade,
        acomodacao = acomodacao,
        nomePassageiro1 = passageiro1?.nome,
        documentoPassageiro1 = passageiro1?.documento,
        numeroDocumentoPassageiro1 = passageiro1?.numeroDocumento,
        dataNascimentoPassageiro1 = passageiro1?.dataNascimento,
        nomePassageiro2 = passageiro2?.nome,
        documentoPassageiro2 = passageiro2?.documento,
        numeroDocumentoPassageiro2 = passageiro2?.numeroDocumento,
        dataNascimentoPassageiro2 = passageiro2?.dataNascimento,
        nomePassageiro3 = passageiro3?.nome,
        tipoDocumentoPassageiro3 = passageiro3?.documento,
        numeroDocumentoPassageiro3 = passageiro3?.numeroDocumento,
        dataNascimentoPassageiro3 = passageiro3?.dataNascimento,
        nomeResponsavelRetirada = veiculo?.nomeResponsavelRetirada,
        documentoResponsavelRetirada = veiculo?.documentoResponsavelRetirada,
        numeroDocumentoResponsavelRetirada = veiculo?.numeroDocumentoResponsavelRetirada,
        tipoVeiculo = veiculo?.tipoVeiculo,
        modeloVeiculo = veiculo?.modeloVeiculo,
        placaVeiculo = veiculo?.placaVeiculo,
        corVeiculo = veiculo?.corVeiculo,
        funcionarioResponsavel = funcionarioResponsavel,
        status = status
    )
}
